-- Fresh seed for testing (LASU + per-level catalog + Week 1 shells).
-- Run after schema.sql. Starter topic notes are created by the API boot
-- seed (notes-engine ensureSeeded), which also backfills legacy content.

insert into universities (name, short_name)
values ('Lagos State University', 'LASU')
on conflict (name) do nothing;

insert into app_settings (key, value)
values ('current_semester', 'First Semester')
on conflict (key) do nothing;

insert into courses (code, title) values
  ('CHM 101', 'General Chemistry I'),
  ('CHM 107', 'General Chemistry Practical I'),
  ('CSC 101', 'Introduction to Computing Science'),
  ('GNS 111', 'Communication in English, Use of Library and ICT'),
  ('MAT 101', 'Elementary Mathematics I (Algebra and Trigonometry)'),
  ('MAT 161', 'Descriptive Statistics'),
  ('MEE 101', 'Engineer in Society'),
  ('MEE 105', 'Engineering Graphics & Solid Modelling I'),
  ('PHY 101', 'General Physics I'),
  ('PHY 107', 'General Physics Practical I'),
  ('AAE 102', 'Introduction to Aerospace Engineering'),
  ('CHM 102', 'General Chemistry II'),
  ('CHM 108', 'General Chemistry Practical II'),
  ('CPE 102', 'Introduction to Chemical & Polymer Engineering'),
  ('GNS 104', 'Use of Yoruba Language and Culture: Basic Communication Concepts'),
  ('GNS 112', 'Nigerian Peoples and Culture'),
  ('MAT 102', 'Elementary Mathematics II (Calculus)'),
  ('MAT 108', 'General Mathematics III (Vectors Geometry and Dynamics)'),
  ('MAT 162', 'Statistical Inference I'),
  ('MEE 104', 'Introduction to Electronics Engineering'),
  ('PHY 102', 'General Physics II'),
  ('PHY 104', 'General Physics Practical II'),
  ('PHY 108', 'General Physics Practical II'),
  ('ASE 201', 'Introduction to Aerospace Systems Engineering II'),
  ('CHE 202', 'CHE 202'),
  ('CHE 204', 'CHE 204'),
  ('CHE 208', 'CHE 208'),
  ('CHE 298', 'CHE 298'),
  ('CHE 299', 'CHE 299'),
  ('CVE 214', 'CVE 214'),
  ('ECE 201', 'Fundamental of Electrical Engineering'),
  ('ECE 203', 'Applied Electricity I'),
  ('ECE 211', 'Computing and Software Engineering'),
  ('ENT 211', 'Entrepreneurship & Innovation'),
  ('IPE 212', 'IPE 212'),
  ('MEE 203', 'Engineering Graphics'),
  ('MEE 205', 'Fundamentals of Fluid Mechanics'),
  ('MEE 207', 'Applied Mechanics'),
  ('MEE 209', 'Engineering Mathematics I'),
  ('ASE 202', 'MATLAB Application to Aerospace Engineering'),
  ('CHE 206', 'Fundamentals Of Thermodynamics'),
  ('ECE 202', 'Engineering Mathematics II'),
  ('ECE 206', 'Electrical Insta IIation Practice Lab'),
  ('ECE 208', 'Electrical And Electronic Drawing'),
  ('ECE 210', 'Fundamental Of Electrical Engineering II'),
  ('ECE 220', 'Introduction to Programming and Computations'),
  ('GNS 212', 'Philosophy Logic and Human Existence and Gender-Based Violence'),
  ('MEE 202', 'Engineering Materials'),
  ('MEE 204', 'Students Workshop Experience'),
  ('MEE 212', 'Mechanics of Machine I'),
  ('ASE 351', 'Aircraft Structural Materials'),
  ('CHE 304', 'CHE 304'),
  ('CHE 306', 'CHE 306'),
  ('CHE 308', 'CHE 308'),
  ('CHE 310', 'CHE 310'),
  ('CHE 312', 'CHE 312'),
  ('CHE 314', 'CHE 314'),
  ('CHE 316', 'CHE 316'),
  ('CPE 398', 'CPE 398'),
  ('ECE 303', 'Electrical Circuit Theory'),
  ('ECE 351', 'Introduction to Artificial Intelligence and Machine Learning'),
  ('GNS 301', 'Logic and Philosophy'),
  ('MEE 301', 'Engineering Mathematics III'),
  ('MEE 305', 'Fluid Mechanics II'),
  ('MEE 351', 'Engineering Statistics & Data Analysis'),
  ('MEE 353', 'Engineering Metallurgy I'),
  ('MEE 355', 'Control System Engineering'),
  ('MEE 357', 'Manufacturing Technology'),
  ('CHE 352', 'Engineering Mathematics IV'),
  ('CVE 304', 'Civil Engineering Materials'),
  ('CVE 308', 'Engineering Survey and Photogrammetry I'),
  ('CVE 310', 'Solid Mechanics'),
  ('ECE 316', 'Electrical Machines'),
  ('ECE 352', 'Technical Writing and Communication'),
  ('ENT 312', 'Venture Creation'),
  ('GNS 312', 'Peace and Conflict Resolution'),
  ('MEE 308', 'Thermo-fluid Laboratory I'),
  ('MEE 352', 'Renewable Energy Systems and Technology'),
  ('MEE 354', 'Computer-Aided Design and Manufacture'),
  ('MEE 398', 'SIWES I (8 Weeks)'),
  ('AAE 421', 'Structural Dynamics'),
  ('CPE 401', 'Chemical Engineering Analysis'),
  ('CPE 403', 'Separation Process III'),
  ('CPE 405', 'Chemical Reaction Engineering I'),
  ('CPE 407', 'Biochemical Engineering I'),
  ('CPE 409', 'Chemical Engineering Lab. III'),
  ('CPE 411', 'Polymer Processing Engineering II'),
  ('CPE 415', 'Polymer Engineering Laboratory III'),
  ('CPE 417', 'Introduction to Plant Design'),
  ('ECE 401', 'Engineering Mathematics V'),
  ('ECE 419', 'Technical Communication'),
  ('ECO 403', 'Economics for Engineers'),
  ('MEE 401', 'Applied Thermodynamics II'),
  ('MEE 403', 'Machine Design II'),
  ('MEE 405', 'Fluid Mechanics III'),
  ('MEE 407', 'Vibrations'),
  ('MEE 411', 'Engineering Materials Selection and Economics'),
  ('MEE 413', 'Technology Policy and Development'),
  ('MEE 415', 'Laboratory Practical'),
  ('AAE 498', 'Industrial Experience (SIWES)'),
  ('ECE 492', 'Application of Engineering Design to Industry'),
  ('MEE 492', 'Application of Engineering Design to Industry'),
  ('MEE 494', 'Safety and Reliability in Nigeria Companies'),
  ('MEE 496', 'Engineering Enterprise'),
  ('MEE 498', 'SIWES III (24 Weeks Compulsory Industrial Attachment)'),
  ('AAE 551', 'Restricted Elective'),
  ('BUL 507', 'Law for Engineers / for Non-Law Students'),
  ('CPE 501', 'Process Control'),
  ('CPE 503', 'Transport Phenomena III'),
  ('CPE 505', 'Environmental Engineering'),
  ('CPE 507', 'Process Design I'),
  ('CPE 509', 'Chemical Reaction Engineering II'),
  ('CPE 515', 'Petrochemical Science and Petroleum Technology'),
  ('CPE 517', 'Pulp and Paper Technology'),
  ('CPE 521', 'Rubber Technology'),
  ('CPE 599', 'Research Project I'),
  ('ECE 502', 'Software Engineering II'),
  ('MEE 501', 'Applied Thermodynamics III'),
  ('MEE 503', 'Machine Design III'),
  ('MEE 505', 'Laboratory Practical'),
  ('MEE 507', 'Advanced Mechanics of Materials I'),
  ('MEE 509', 'Advanced Fluid Mechanics I'),
  ('MEE 511', 'Heat and Mass Transfer'),
  ('MEE 513', 'Mechanics of Metal Forming I'),
  ('MEE 515', 'Maintenance Engineering'),
  ('MEE 517', 'Fluid Machinery'),
  ('MEE 519', 'Iron Making'),
  ('MEE 521', 'Refractory Technology'),
  ('MEE 523', 'Project Drafting Lab.'),
  ('MEE 525', 'Air-Conditioning and Refrigeration'),
  ('MEE 535', 'Production Engineering I'),
  ('MEE 599', 'Project I'),
  ('ASE 508', 'Airline Enterprise Operations'),
  ('CPE 502', 'Process Optimization'),
  ('CPE 504', 'Safety and Loss Prevention'),
  ('CPE 506', 'Biochemical Engineering II'),
  ('CPE 508', 'Process Design II'),
  ('CPE 510', 'Process Control II'),
  ('CPE 516', 'Reservoir Engineering'),
  ('CPE 518', 'Industrial Chemistry'),
  ('CPE 520', 'Medical Application of Polymer'),
  ('CPE 598', 'Research Project II'),
  ('ENT 1000', 'Professional Entrepreneurship'),
  ('MEE 502', 'Engineering Management'),
  ('MEE 504', 'Energy Sources and Conversion'),
  ('MEE 506', 'Thermal Engines'),
  ('MEE 508', 'Operational Research'),
  ('MEE 510', 'Advance Fluid Mechanics II'),
  ('MEE 512', 'Mechanics of Metal Forming II'),
  ('MEE 514', 'Advanced Mechanics of Materials II'),
  ('MEE 516', 'Production Engineering II'),
  ('MEE 518', 'Industrial Engineering'),
  ('MEE 520', 'Steel Making'),
  ('MEE 524', 'Foundry Technology'),
  ('MEE 526', 'Engineering Systems Analysis'),
  ('MEE 528', 'Engineering Metallurgy II'),
  ('MEE 534', 'Advanced CAD/CAM'),
  ('MEE 598', 'Project II')
on conflict (code) do nothing;

insert into course_levels (course, level, semester) values
  ('CHM 101', '100 Level', 'First Semester'),
  ('CHM 107', '100 Level', 'First Semester'),
  ('CSC 101', '100 Level', 'First Semester'),
  ('GNS 111', '100 Level', 'First Semester'),
  ('MAT 101', '100 Level', 'First Semester'),
  ('MAT 161', '100 Level', 'First Semester'),
  ('MEE 101', '100 Level', 'First Semester'),
  ('MEE 105', '100 Level', 'First Semester'),
  ('PHY 101', '100 Level', 'First Semester'),
  ('PHY 107', '100 Level', 'First Semester'),
  ('AAE 102', '100 Level', 'Second Semester'),
  ('CHM 102', '100 Level', 'Second Semester'),
  ('CHM 108', '100 Level', 'Second Semester'),
  ('CPE 102', '100 Level', 'Second Semester'),
  ('GNS 104', '100 Level', 'Second Semester'),
  ('GNS 112', '100 Level', 'Second Semester'),
  ('MAT 102', '100 Level', 'Second Semester'),
  ('MAT 108', '100 Level', 'Second Semester'),
  ('MAT 162', '100 Level', 'Second Semester'),
  ('MEE 104', '100 Level', 'Second Semester'),
  ('PHY 102', '100 Level', 'Second Semester'),
  ('PHY 104', '100 Level', 'Second Semester'),
  ('PHY 108', '100 Level', 'Second Semester'),
  ('ASE 201', '200 Level', 'First Semester'),
  ('CHE 202', '200 Level', 'First Semester'),
  ('CHE 204', '200 Level', 'First Semester'),
  ('CHE 208', '200 Level', 'First Semester'),
  ('CHE 298', '200 Level', 'First Semester'),
  ('CHE 299', '200 Level', 'First Semester'),
  ('CVE 214', '200 Level', 'First Semester'),
  ('ECE 201', '200 Level', 'First Semester'),
  ('ECE 203', '200 Level', 'First Semester'),
  ('ECE 211', '200 Level', 'First Semester'),
  ('ENT 211', '200 Level', 'First Semester'),
  ('IPE 212', '200 Level', 'First Semester'),
  ('MEE 203', '200 Level', 'First Semester'),
  ('MEE 205', '200 Level', 'First Semester'),
  ('MEE 207', '200 Level', 'First Semester'),
  ('MEE 209', '200 Level', 'First Semester'),
  ('ASE 202', '200 Level', 'Second Semester'),
  ('CHE 206', '200 Level', 'Second Semester'),
  ('ECE 202', '200 Level', 'Second Semester'),
  ('ECE 206', '200 Level', 'Second Semester'),
  ('ECE 208', '200 Level', 'Second Semester'),
  ('ECE 210', '200 Level', 'Second Semester'),
  ('ECE 220', '200 Level', 'Second Semester'),
  ('GNS 212', '200 Level', 'Second Semester'),
  ('MEE 202', '200 Level', 'Second Semester'),
  ('MEE 204', '200 Level', 'Second Semester'),
  ('MEE 212', '200 Level', 'Second Semester'),
  ('ASE 351', '300 Level', 'First Semester'),
  ('CHE 304', '300 Level', 'First Semester'),
  ('CHE 306', '300 Level', 'First Semester'),
  ('CHE 308', '300 Level', 'First Semester'),
  ('CHE 310', '300 Level', 'First Semester'),
  ('CHE 312', '300 Level', 'First Semester'),
  ('CHE 314', '300 Level', 'First Semester'),
  ('CHE 316', '300 Level', 'First Semester'),
  ('CPE 398', '300 Level', 'First Semester'),
  ('ECE 303', '300 Level', 'First Semester'),
  ('ECE 351', '300 Level', 'First Semester'),
  ('GNS 301', '300 Level', 'First Semester'),
  ('MEE 301', '300 Level', 'First Semester'),
  ('MEE 305', '300 Level', 'First Semester'),
  ('MEE 351', '300 Level', 'First Semester'),
  ('MEE 353', '300 Level', 'First Semester'),
  ('MEE 355', '300 Level', 'First Semester'),
  ('MEE 357', '300 Level', 'First Semester'),
  ('CHE 352', '300 Level', 'Second Semester'),
  ('CVE 304', '300 Level', 'Second Semester'),
  ('CVE 308', '300 Level', 'Second Semester'),
  ('CVE 310', '300 Level', 'Second Semester'),
  ('ECE 316', '300 Level', 'Second Semester'),
  ('ECE 352', '300 Level', 'Second Semester'),
  ('ENT 312', '300 Level', 'Second Semester'),
  ('GNS 312', '300 Level', 'Second Semester'),
  ('MEE 308', '300 Level', 'Second Semester'),
  ('MEE 352', '300 Level', 'Second Semester'),
  ('MEE 354', '300 Level', 'Second Semester'),
  ('MEE 398', '300 Level', 'Second Semester'),
  ('AAE 421', '400 Level', 'First Semester'),
  ('CPE 401', '400 Level', 'First Semester'),
  ('CPE 403', '400 Level', 'First Semester'),
  ('CPE 405', '400 Level', 'First Semester'),
  ('CPE 407', '400 Level', 'First Semester'),
  ('CPE 409', '400 Level', 'First Semester'),
  ('CPE 411', '400 Level', 'First Semester'),
  ('CPE 415', '400 Level', 'First Semester'),
  ('CPE 417', '400 Level', 'First Semester'),
  ('ECE 401', '400 Level', 'First Semester'),
  ('ECE 419', '400 Level', 'First Semester'),
  ('ECO 403', '400 Level', 'First Semester'),
  ('MEE 401', '400 Level', 'First Semester'),
  ('MEE 403', '400 Level', 'First Semester'),
  ('MEE 405', '400 Level', 'First Semester'),
  ('MEE 407', '400 Level', 'First Semester'),
  ('MEE 411', '400 Level', 'First Semester'),
  ('MEE 413', '400 Level', 'First Semester'),
  ('MEE 415', '400 Level', 'First Semester'),
  ('AAE 498', '400 Level', 'Second Semester'),
  ('ECE 492', '400 Level', 'Second Semester'),
  ('MEE 492', '400 Level', 'Second Semester'),
  ('MEE 494', '400 Level', 'Second Semester'),
  ('MEE 496', '400 Level', 'Second Semester'),
  ('MEE 498', '400 Level', 'Second Semester'),
  ('AAE 551', '500 Level', 'First Semester'),
  ('BUL 507', '500 Level', 'First Semester'),
  ('CPE 501', '500 Level', 'First Semester'),
  ('CPE 503', '500 Level', 'First Semester'),
  ('CPE 505', '500 Level', 'First Semester'),
  ('CPE 507', '500 Level', 'First Semester'),
  ('CPE 509', '500 Level', 'First Semester'),
  ('CPE 515', '500 Level', 'First Semester'),
  ('CPE 517', '500 Level', 'First Semester'),
  ('CPE 521', '500 Level', 'First Semester'),
  ('CPE 599', '500 Level', 'First Semester'),
  ('ECE 502', '500 Level', 'First Semester'),
  ('MEE 501', '500 Level', 'First Semester'),
  ('MEE 503', '500 Level', 'First Semester'),
  ('MEE 505', '500 Level', 'First Semester'),
  ('MEE 507', '500 Level', 'First Semester'),
  ('MEE 509', '500 Level', 'First Semester'),
  ('MEE 511', '500 Level', 'First Semester'),
  ('MEE 513', '500 Level', 'First Semester'),
  ('MEE 515', '500 Level', 'First Semester'),
  ('MEE 517', '500 Level', 'First Semester'),
  ('MEE 519', '500 Level', 'First Semester'),
  ('MEE 521', '500 Level', 'First Semester'),
  ('MEE 523', '500 Level', 'First Semester'),
  ('MEE 525', '500 Level', 'First Semester'),
  ('MEE 535', '500 Level', 'First Semester'),
  ('MEE 599', '500 Level', 'First Semester'),
  ('ASE 508', '500 Level', 'Second Semester'),
  ('CPE 502', '500 Level', 'Second Semester'),
  ('CPE 504', '500 Level', 'Second Semester'),
  ('CPE 506', '500 Level', 'Second Semester'),
  ('CPE 508', '500 Level', 'Second Semester'),
  ('CPE 510', '500 Level', 'Second Semester'),
  ('CPE 516', '500 Level', 'Second Semester'),
  ('CPE 518', '500 Level', 'Second Semester'),
  ('CPE 520', '500 Level', 'Second Semester'),
  ('CPE 598', '500 Level', 'Second Semester'),
  ('ENT 1000', '500 Level', 'Second Semester'),
  ('MEE 502', '500 Level', 'Second Semester'),
  ('MEE 504', '500 Level', 'Second Semester'),
  ('MEE 506', '500 Level', 'Second Semester'),
  ('MEE 508', '500 Level', 'Second Semester'),
  ('MEE 510', '500 Level', 'Second Semester'),
  ('MEE 512', '500 Level', 'Second Semester'),
  ('MEE 514', '500 Level', 'Second Semester'),
  ('MEE 516', '500 Level', 'Second Semester'),
  ('MEE 518', '500 Level', 'Second Semester'),
  ('MEE 520', '500 Level', 'Second Semester'),
  ('MEE 524', '500 Level', 'Second Semester'),
  ('MEE 526', '500 Level', 'Second Semester'),
  ('MEE 528', '500 Level', 'Second Semester'),
  ('MEE 534', '500 Level', 'Second Semester'),
  ('MEE 598', '500 Level', 'Second Semester')
on conflict (course, level) do nothing;

insert into weeks (course, week, title, subtitle, note_json)
select c.code, 1, 'Week 1', 'Starter note',
  jsonb_build_object('course', c.code, 'week', 1, 'title', 'Week 1', 'subtitle', 'Starter note', 'topics', '[]'::jsonb, 'eoq', jsonb_build_object('questions', '[]'::jsonb))
from courses c
on conflict (course, week) do nothing;

-- Default platform admin. Email: unify.admin@unify.learn / Password: unify.admin
-- CHANGE THE PASSWORD right after first login (Supabase > Auth > Users > ... > Send reset).
-- Idempotent: does nothing if the account already exists (never resets your password).
create extension if not exists pgcrypto;
do $$
declare
  admin_id uuid;
begin
  if not exists (select 1 from auth.users where email = 'unify.admin@unify.learn') then
    admin_id := gen_random_uuid();
    insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
    values ('00000000-0000-0000-0000-000000000000', admin_id, 'authenticated', 'authenticated', 'unify.admin@unify.learn', crypt('unify.admin', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{}', now(), now());
    insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
    values (gen_random_uuid(), admin_id, admin_id, jsonb_build_object('sub', admin_id, 'email', 'unify.admin@unify.learn'), 'email', now(), now(), now());
    insert into public.profiles (id, first_name, email, role, is_admin)
    values (admin_id, 'Unify Admin', 'unify.admin@unify.learn', 'collaborator', true);
  end if;
end $$;
